### ISSUE TITLE
Graphics roadmap

### ISSUE THREAD

**Issue by ninpnin** [ninpnin/blockshead#4]
- [x] Sketch versions of original character
- [ ] Vectorized versions of original character
- [ ] Sketch versions of custom character
- [ ] Finalized versions of custom character
- [x] Sketch versions of original opponents
- [ ] Finalized versions of original opponents
- [ ] Comic versions of weapons
- [ ] Sketch versions of map and surroundings
- [ ] Final versions of map and surroundings
