### ISSUE TITLE
Mechanics roadmap

### ISSUE THREAD

**Issue by ninpnin** [ninpnin/blockshead#5]
- [x] Moving the character
- [x] Collisions
- [x] Health
- [x] Shooting
- [x] Simple opponent AI
- [ ] Sophisticated opponent AI
- [x] Pausing the game
- [x] Obstacles
- [x] Health boxes
