### ISSUE TITLE
Maps roadmap

### ISSUE THREAD

**Issue by ninpnin** [ninpnin/blockshead#6]
- [x] Implement mostly functional draft map 
- [ ] Implement one functional map
- [ ] Create a proof of concept of a custom map
- [ ] Multiple custom maps in different settings
